spring: 
  datasource:
    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))(CONNECT_DATA = (SID = XE)))
    username: AUTH
    password: welcome
    platform: oracle
    initialization-mode: always